#!/bin/bash
env=uat
if [ "$env" == "qa" ]
then
        touch qa-env
        cp qa-env /tmp/
        ls -l /tmp/qa-env
elif [ "$env" == "uat" ]
then
        touch uat-env
        cp uat-env /tmp/
        ls -l /tmp/uat-env
elif [ "$env" == "prod" ]
then
        touch prod-env
        cp prod-env /tmp/
        ls -l /tmp/prod-env
else
        echo "$env provided env conditions is not available"
fi
